//go:build e2e

package e2e

import (
	"context"
	"encoding/json"
	"net"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"testing"
	"time"
)

// Test_Users_ranwei_workspace_go_work_seargo_internal_engine_E2E builds and launches the server as a real subprocess, then
// exercises its external HTTP interface and asserts on the parsed JSON response.
//
// AUTO-GENERATED by RunE2ETests (Go http-server template).
// TODO: adjust buildTarget, the request path, and the response assertions to
// match the real service under test.
func Test_Users_ranwei_workspace_go_work_seargo_internal_engine_E2E(t *testing.T) {
	moduleRoot := "/Users/ranwei/workspace/go_work/seargo"
	buildTarget := "." // e.g. "." or "./cmd/server"

	freePort := func() string {
		l, err := net.Listen("tcp", "127.0.0.1:0")
		if err != nil {
			t.Fatalf("failed to find a free port: %v", err)
		}
		defer l.Close()
		_, port, _ := net.SplitHostPort(l.Addr().String())
		return port
	}
	waitForServer := func(addr string, timeout time.Duration) {
		deadline := time.Now().Add(timeout)
		for time.Now().Before(deadline) {
			conn, err := net.DialTimeout("tcp", addr, 200*time.Millisecond)
			if err == nil {
				_ = conn.Close()
				return
			}
			time.Sleep(100 * time.Millisecond)
		}
		t.Fatalf("server did not become ready at %s within %s", addr, timeout)
	}

	// 1. Build the server binary.
	binPath := filepath.Join(t.TempDir(), "server-under-test")
	build := exec.Command("go", "build", "-o", binPath, buildTarget)
	build.Dir = moduleRoot
	if out, err := build.CombinedOutput(); err != nil {
		t.Fatalf("go build failed: %v\n%s", err, out)
	}

	// 2. Pick a free port and launch the server as a real subprocess.
	port := freePort()
	addr := "127.0.0.1:" + port
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	cmd := exec.CommandContext(ctx, binPath)
	cmd.Dir = moduleRoot
	// TODO: pass the listen address the way your server expects it.
	cmd.Env = append(os.Environ(), "PORT="+port, "ADDR="+addr)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Start(); err != nil {
		t.Fatalf("failed to start server: %v", err)
	}
	t.Cleanup(func() {
		cancel()
		_ = cmd.Wait()
	})

	// 3. Wait until the server is accepting connections.
	waitForServer(addr, 10*time.Second)

	// 4. Call the external interface and parse the JSON response.
	client := &http.Client{Timeout: 5 * time.Second}
	req, err := http.NewRequest(http.MethodGet, "http://"+addr+"/", nil) // TODO: real method + path
	if err != nil {
		t.Fatalf("failed to build request: %v", err)
	}
	// TODO: if this endpoint requires authentication, attach a valid credential.
	// Obtain it the way your service expects — e.g. a test token injected into the
	// server via cmd.Env above, or by calling your login endpoint first, then:
	//   req.Header.Set("Authorization", "Bearer "+token)
	resp, err := client.Do(req)
	if err != nil {
		t.Fatalf("request failed: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		t.Fatalf("unexpected status: got %d, want 200", resp.StatusCode)
	}

	var body map[string]any
	if err := json.NewDecoder(resp.Body).Decode(&body); err != nil {
		t.Fatalf("failed to decode JSON response: %v", err)
	}

	// TODO: assert on the fields your interface returns, e.g.:
	//   if body["status"] != "ok" { t.Fatalf("got %v", body["status"]) }
	_ = body

	// TODO: if the endpoint is protected, also assert the unauthorized path:
	//   unauth, _ := http.NewRequest(http.MethodGet, "http://"+addr+"/", nil)
	//   if r2, err := client.Do(unauth); err == nil {
	//       defer r2.Body.Close()
	//       if r2.StatusCode != http.StatusUnauthorized {
	//           t.Fatalf("want 401 without credentials, got %d", r2.StatusCode)
	//       }
	//   }
}
