package config

func builtInDefaults() Config {
	return Config{
		General: GeneralConfig{
			Debug:         false,
			InstanceName:  "SearGo",
			DonationURL:   "https://docs.searxng.org/donate.html",
			EnableMetrics: true,
		},
		Brand: BrandConfig{
			IssueURL:        "https://github.com/searxng/searxng/issues",
			DocsURL:         "https://docs.searxng.org",
			PublicInstances: "https://searx.space",
			WikiURL:         "https://github.com/searxng/searxng/wiki",
			NewIssueURL:     "https://github.com/searxng/searxng/issues/new",
			Custom:          BrandCustom{Links: map[string]string{}},
			PWAColors: ThemeColors{
				ThemeColorLight:      "#3050ff",
				BackgroundColorLight: "#fff",
				ThemeColorDark:       "#58f",
				BackgroundColorDark:  "#222428",
				ThemeColorBlack:      "#3050ff",
				BackgroundColorBlack: "#000",
			},
		},
		Search: SearchConfig{
			SafeSearch:       0,
			Autocomplete:     "",
			AutocompleteMin:  4,
			FaviconResolver:  "",
			DefaultLang:      "",
			Languages:        []string{"zh-CN", "en", "en-US"},
			DefaultCategory:  "general",
			MaxResults:       10,
			BanTimeOnFail:    5.0,
			MaxBanTimeOnFail: 120.0,
			Formats:          []string{"html", "json"},
			MaxPage:          0,
			SuspendedTimes: SuspendedTimesConfig{
				SearxEngineAccessDenied:     86400,
				SearxEngineCaptcha:          86400,
				SearxEngineTooManyRequests:  3600,
				CfSearxEngineCaptcha:        1296000,
				CfSearxEngineAccessDenied:   86400,
				RecaptchaSearxEngineCaptcha: 604800,
			},
		},
		Server: ServerConfig{
			Port:                8888,
			BindAddress:         "127.0.0.1",
			Limiter:             false,
			PublicInstance:      false,
			HTTPProtocolVersion: "1.0",
			Method:              "POST",
			DefaultHTTPHeaders:  map[string]string{},
			TrustedProxies:      []string{"127.0.0.0/8", "::1"},
		},
		Outgoing: OutgoingConfig{
			RequestTimeout:  3.0,
			EnableHTTP2:     true,
			Verify:          true,
			PoolConnections: 100,
			PoolMaxsize:     10,
			KeepaliveExpiry: 5.0,
			MaxRedirects:    30,
			Retries:         0,
			UsingTorProxy:   false,
		},
		UI: UIConfig{
			DefaultTheme:           "simple",
			CacheURL:               "https://web.archive.org/web/",
			SearchOnCategorySelect: true,
			Hotkeys:                "default",
			URLFormatting:          "pretty",
			ThemeArgs:              UIThemeArgs{SimpleStyle: "auto"},
		},
		Preferences: PreferencesConfig{
			Lock: []string{},
		},
		Valkey:           ValkeyConfig{},
		Storage:          StorageConfig{Backend: "memory"},
		Plugins:          map[string]PluginConfig{},
		Answerers:        map[string]AnswererConfig{},
		CategoriesAsTabs: map[string]CategoryTabConfig{},
		Engines:          []EngineConfig{},
		DOIRsolvers:      map[string]string{},
		DefaultDOIResolver: "oadoi.org",
	}
}
